package org.saJava.GUI;

import org.saJava.connect.WizCON;
import org.saJava.preferences.UserSettings;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Vector;

/**
 * Created with IntelliJ IDEA.
 * User: Goldberg
 * Date: 3/7/13
 * Time: 8:55 PM
 * To change this template use File | Settings | File Templates.
 */
public class ShowUsage extends JDialog{
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static String selectMonth;
    JDialog dialog=this;


    public ShowUsage() {
        setBounds(400,200,300,300);
        setDefaultLookAndFeelDecorated(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Usage Detail");
        initComponents();

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To change body of implemented methods use File | Settings | File Templates.
                dispose();
                String index=Integer.toString(jComboBox1.getSelectedIndex());
                selectMonth=jComboBox1.getSelectedItem().toString();

                String monthIndex=Integer.toString(jComboBox1.getSelectedIndex()+1);
                new UsageProg(index,monthIndex,selectMonth).setVisible(true);
                /*UserSettings settings=new UserSettings();
                settings.setPreference();

                if(WizCON.sessionDetails(settings.prefs.get(settings.pUname,""),index,monthIndex))
                    new UsageTable().setVisible(true);
                else if(WizCON.message.equals("connectTimeOut")){
                    JOptionPane.showMessageDialog(dialog,"Server Down.Try Later.");
                    dispose();
                    new ShowUsage().setVisible(true);
                }
                else if(WizCON.message.equals("noData")) {
                    {
                        JOptionPane.showMessageDialog(dialog,"No Data Available for this month");
                        dispose();
                        new ShowUsage().setVisible(true);
                    }
                } */
            }
        });

        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //To change body of implemented methods use File | Settings | File Templates.
                dispose();
                new Progress("Fetching Data").setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ImageIcon icon=new ImageIcon(getClass().getResource("image/magic.png"));
        jLabel1 = new javax.swing.JLabel(icon);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        UserSettings settings=new UserSettings();
        settings.setPreference();

        jLabel2.setText("Hello");

        jLabel3.setText(settings.prefs.get(settings.pUname,""));

         String[] lmonths = {"January","February","March","April","May","June","July",
                            "Aug","Septe","Octo","Nov","Dece"};


        Vector comboItems=new Vector();
        for(String month:WizCON.months){
           for(String m:lmonths){
                if(month.contains(m))     {
                    System.out.print(month+" "+m);
                    comboItems.add(month);
                    break;
                }
            }
            /*System.out.print(month);
           comboItems.add(month); */

        }

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(comboItems));



        jButton1.setText("Submit");

        jButton2.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addGap(104, 104, 104))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{jButton1, jComboBox1});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jButton1, jComboBox1});

        pack();
    }// </editor-fold>
}
